# Generated by Django 3.0.7 on 2020-06-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addmovieform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddMovieForm',
            new_name='AddMovie',
        ),
    ]
