# Generated by Django 3.0.7 on 2020-06-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200606_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddMovie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
